import asyncio
import functools
import logging
import os
import sys
from pathlib import Path

from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from background_tasks import track_task
from downloader import DownloadOrchestrator, check_ffmpeg_available, probe_total_bytes
from gumroad_client import GumroadClientError, verify_license
from history_routes import build_history_router
from history_store import HistoryStore, redact_pro_summary_fields
from key_test_routes import build_key_test_router
from license_config import DEV_LICENSE_KEY
from license_routes import build_license_router
from license_store import LicenseStore
from queue_manager import QueueManager
from queue_routes import AppState, build_queue_router
from settings_routes import build_settings_router
from settings_store import SettingsStore
from transcription import TranscriptionOrchestrator
from transcription_routes import build_transcription_router
from usage_routes import build_usage_router
from usage_store import UsageStore
from ws_manager import ConnectionManager, QueueBroadcaster

DB_PATH = os.environ.get(
    "CLIP_PULL_DB_PATH", str(Path(__file__).parent / "data" / "clip_pull.db")
)

# The packaged app has no visible console (stdio is hidden), so a plain
# print()/stderr warning is invisible to end users and to us -- everything
# meaningful goes to a log file next to the database instead. Skipped for
# ":memory:" (test) DB paths so the test suite doesn't scatter log files.
logger = logging.getLogger("clippull")
logger.setLevel(logging.INFO)
if DB_PATH != ":memory:":
    log_dir = Path(DB_PATH).parent
    log_dir.mkdir(parents=True, exist_ok=True)
    file_handler = logging.FileHandler(log_dir / "clippull.log", encoding="utf-8")
    file_handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s"))
    logger.addHandler(file_handler)
stream_handler = logging.StreamHandler(sys.stderr)
stream_handler.setFormatter(logging.Formatter("%(levelname)s %(name)s: %(message)s"))
logger.addHandler(stream_handler)

app = FastAPI()
# CORS stays wide open deliberately: the renderer loads over file:// (an
# origin CORSMiddleware can't reliably allowlist by name across Electron/
# Chromium versions), and restricting this list buys nothing on its own --
# the actual gate against "any webpage the user happens to have open can
# also reach this 127.0.0.1-bound API" is API_TOKEN below, checked on every
# request regardless of origin. See require_api_token.
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# A fresh random secret generated by main.js on every app launch (passed
# down via this env var) and required on every request below except
# /health. Binding to 127.0.0.1 alone is NOT sufficient isolation: browsers
# happily let a webpage fetch() a localhost server and, combined with the
# CORS config above, read the response too -- this token is what actually
# stops an arbitrary website from reading API keys out of /settings,
# writing files via /queue, or wiping /history while the app is running.
# Unset (local `python main.py` runs outside Electron, and the pytest
# suite, neither of which go through main.js) means auth is a no-op --
# logged loudly since that should never be true for a real user's install.
API_TOKEN = os.environ.get("CLIP_PULL_API_TOKEN")

connection_manager = ConnectionManager()
broadcaster = QueueBroadcaster(connection_manager)

history_store = HistoryStore(DB_PATH)
settings_store = SettingsStore(DB_PATH)
license_store = LicenseStore(DB_PATH)
usage_store = UsageStore(DB_PATH)


def record_history_and_broadcast(**kwargs) -> dict:
    # Finished downloads only land in the History tab via this WS push —
    # without it, History only ever updates on the next manual refresh/search.
    row = history_store.record(**kwargs)
    # A retry re-recorded into an existing row (update_id) can carry over a
    # summary from a previous attempt -- redact the same way GET /history
    # does, so a non-Pro caller can't see Pro-only content via this broadcast
    # either.
    broadcast_row = redact_pro_summary_fields(row, license_store.is_pro())
    track_task(
        asyncio.create_task(
            connection_manager.broadcast({"type": "history_added", "entry": broadcast_row})
        )
    )
    _maybe_auto_transcribe(row)
    return row


def _maybe_auto_transcribe(row: dict) -> None:
    # Kick off transcription (and optionally a chained summary) for a
    # just-finished download when a Pro user has opted into auto-processing.
    # The whole decision is wrapped so any failure here is logged but NEVER
    # propagates: the download has already been recorded/broadcast as done by
    # this point (the actually-important outcome), and a bug in this
    # convenience trigger must not undo that. Reuses the same orchestrator
    # methods the manual transcribe/summarize routes call -- just from an
    # automatic trigger point instead of an HTTP POST.
    try:
        if row.get("status") != "done":
            return
        settings = settings_store.get()
        if not settings.get("auto_transcribe_on_download"):
            return
        if not license_store.is_pro():
            return
        history_id = row["id"]
        if not transcription_orchestrator.request_transcription(history_id):
            return
        try:
            transcription_orchestrator.mark_transcription_running(history_id)
            summarize = bool(settings.get("auto_summarize_after_transcribe"))
            track_task(
                asyncio.create_task(
                    transcription_orchestrator.transcribe_and_maybe_summarize(history_id, summarize)
                )
            )
        except Exception:
            # request_transcription() above already reserved this entry's
            # slot -- if anything here fails before a task actually gets
            # created to eventually release it, that reservation would
            # otherwise stick around forever, permanently blocking this
            # entry from ever being transcribed again this session.
            transcription_orchestrator.release_transcription(history_id)
            raise
    except Exception:
        logger.exception("Auto-transcribe trigger failed for history entry %s", row.get("id"))


queue_manager = QueueManager(on_update=broadcaster.notify, on_remove=broadcaster.notify_removed)
orchestrator = DownloadOrchestrator(
    queue_manager,
    probe_fn=probe_total_bytes,
    get_max_concurrent=lambda: settings_store.get()["max_concurrent_downloads"],
    get_fragment_concurrency=lambda: settings_store.get()["concurrent_fragment_downloads"],
    get_aria2c_enabled=lambda: settings_store.get()["aria2c_enabled"],
    record_history=record_history_and_broadcast,
    on_batch_complete=lambda batch_id, summary: track_task(
        asyncio.create_task(
            connection_manager.broadcast(
                {"type": "batch_complete", "batch_id": batch_id, "summary": summary}
            )
        )
    ),
)

state = AppState()

transcription_orchestrator = TranscriptionOrchestrator(
    history_store,
    settings_store,
    usage_store=usage_store,
    license_store=license_store,
    broadcast=lambda message: track_task(
        asyncio.create_task(connection_manager.broadcast(message))
    ),
)

app.include_router(
    build_queue_router(queue_manager, orchestrator, history_store, settings_store, state)
)
app.include_router(build_history_router(history_store, license_store))
app.include_router(build_settings_router(settings_store))
app.include_router(build_key_test_router())
app.include_router(build_license_router(license_store))
app.include_router(build_usage_router(usage_store, license_store))
app.include_router(
    build_transcription_router(
        history_store, transcription_orchestrator, license_store, settings_store
    )
)


async def _revalidate_license(store: LicenseStore) -> None:
    # Opportunistic re-check of a cached-active license, run as a fire-and-forget
    # startup task. verify_license does a blocking httpx call, so -- exactly like
    # transcription's AI-client calls -- it runs in a thread executor to avoid
    # blocking the event loop. A network failure leaves the cached status alone
    # (offline grace: don't revoke Pro just because the user is offline); only a
    # definitive answer from Gumroad updates the cache.
    license_key = store.get_license_key()
    if not license_key:
        return
    # Same dev-only bypass as the /license/activate route (see
    # license_config.py) -- without this, a license activated locally via
    # CLIP_PULL_DEV_LICENSE_KEY gets silently revoked on the very next
    # backend restart, since Gumroad has never heard of the dev key and
    # would otherwise reject it here.
    if DEV_LICENSE_KEY and license_key == DEV_LICENSE_KEY:
        store.touch_validated()
        return
    loop = asyncio.get_running_loop()
    try:
        result = await loop.run_in_executor(
            None, functools.partial(verify_license, license_key, increment_uses_count=False)
        )
    except GumroadClientError as exc:
        logger.info("Skipping license revalidation -- couldn't reach Gumroad (%s).", exc)
        return

    purchase = result.get("purchase") or {}
    if not result.get("success") or (
        purchase.get("refunded") or purchase.get("chargebacked") or purchase.get("disputed")
    ):
        store.set_invalid()
    else:
        store.touch_validated()


@app.middleware("http")
async def require_api_token(request: Request, call_next):
    # No token configured -- see API_TOKEN's comment above: this is expected
    # for the pytest suite and a manual `python main.py` run, never for the
    # packaged/Electron-launched app, which always sets one.
    if not API_TOKEN:
        return await call_next(request)
    # /health is polled by main.js before the window (and its token) even
    # exists, and reveals nothing beyond "the process is up". CORS preflight
    # (OPTIONS) requests never carry the app's custom header by spec -- they
    # carry no route logic of their own either, so exempting them is safe;
    # CORSMiddleware (registered first, so it wraps this middleware) answers
    # those directly in the common case anyway.
    if request.url.path == "/health" or request.method == "OPTIONS":
        return await call_next(request)
    if request.headers.get("x-clip-pull-token") != API_TOKEN:
        return JSONResponse(status_code=401, content={"detail": "Missing or invalid API token."})
    return await call_next(request)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket) -> None:
    # BaseHTTPMiddleware (require_api_token above) only wraps the HTTP
    # request/response cycle -- WebSocket connections bypass it entirely, so
    # this route checks the same token itself. Browsers' WebSocket
    # constructor can't set custom headers, so the token rides as a query
    # param instead (see frontend/ws-client.js).
    if API_TOKEN and websocket.query_params.get("token") != API_TOKEN:
        await websocket.close(code=1008)  # 1008 = policy violation
        return
    await connection_manager.connect(websocket)
    try:
        # Kept inside the try so a disconnect during this initial sync send
        # is caught like any other, and the finally below still removes the
        # connection from the broadcast list.
        await websocket.send_json({"type": "sync", "entries": queue_manager.to_list()})
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        pass
    except Exception:
        # Any other transport-level error (not a clean WebSocketDisconnect)
        # still needs the connection removed from the broadcast list -- left
        # unhandled, broadcast()'s own dead-connection cleanup would
        # eventually self-heal this, but only on the next message sent.
        pass
    finally:
        connection_manager.disconnect(websocket)


if __name__ == "__main__":
    import uvicorn

    if not API_TOKEN:
        logger.warning(
            "CLIP_PULL_API_TOKEN is not set -- API authentication is DISABLED. "
            "Every route (including plaintext AI provider keys in /settings) is "
            "reachable by anything that can reach 127.0.0.1:8934, including a "
            "webpage open in the user's browser. This is expected for a manual "
            "`python main.py` run or the test suite; it must NEVER happen for "
            "the packaged app, which always sets this env var itself."
        )

    if not check_ffmpeg_available():
        logger.warning(
            "ffmpeg not found on PATH. Downloads will use a single "
            "pre-muxed format instead of the highest available quality."
        )

    reset_count = history_store.reset_stuck_transcriptions()
    if reset_count:
        logger.warning(
            "Reset %d transcription(s) left stuck on 'running' from a previous session.",
            reset_count,
        )

    # A real HTTP re-check can't run in this synchronous pre-startup block
    # without blocking app launch, so schedule it as a fire-and-forget task
    # once the event loop is running -- and only if a license is cached active.
    @app.on_event("startup")
    async def revalidate_license_on_startup() -> None:
        if license_store.get()["status"] == "active":
            track_task(asyncio.create_task(_revalidate_license(license_store)))

    # main.js's exit handler already sees this process's exit code/signal,
    # but not *why* -- a packaged Windows GUI app has no console, so without
    # this, an unhandled exception here (or uvicorn failing to even bind)
    # left nothing behind to diagnose beyond "it stopped." Logged through the
    # existing `logger` so it lands in clippull.log alongside everything
    # else that was happening right before the crash, then re-raised so the
    # process still exits non-zero exactly as before -- this only adds a
    # paper trail, it doesn't change the failure behavior itself.
    try:
        uvicorn.run(app, host="127.0.0.1", port=8934)
    except OSError:
        logger.exception(
            "uvicorn.run() failed to start -- port 8934 may already be in use "
            "by another process (a stuck previous instance, or a second copy "
            "of CLIP.PULL already running)."
        )
        raise
    except Exception:
        logger.exception("Backend crashed while running uvicorn.run().")
        raise
